// GENERATED from the BuildAndBreach Unity project's in-game build-menu
// thumbnails (Assets/Resources/Thumbnails, downscaled to 128px) — the same
// renders the headset shows, so the palette here and the in-game menu read as
// one catalog. Keyed by palette `kind`. Regenerate by re-running the copy in
// tools/measure-footprints.py's README block if the catalog changes.
// Walls and the start marker have no thumbnails (they stay color swatches).
declare const require: (path: string) => number; // Metro asset require (no node types here)

export const THUMBS: Record<string, number> = {
  "BathTub02": require("./BathTub02.png"),
  "BathTub05": require("./BathTub05.png"),
  "BathTub06": require("./BathTub06.png"),
  "BathTub07": require("./BathTub07.png"),
  "BathroomVanity01": require("./BathroomVanity01.png"),
  "BathroomVanity02": require("./BathroomVanity02.png"),
  "BathroomVanity03": require("./BathroomVanity03.png"),
  "BathroomVanity04": require("./BathroomVanity04.png"),
  "BathroomVanity05": require("./BathroomVanity05.png"),
  "BathroomVanity06": require("./BathroomVanity06.png"),
  "BathroomVanity07": require("./BathroomVanity07.png"),
  "Bed01": require("./Bed01.png"),
  "Bed02": require("./Bed02.png"),
  "Bed03": require("./Bed03.png"),
  "Bed04": require("./Bed04.png"),
  "Bed05": require("./Bed05.png"),
  "Black Door": require("./Black_Door.png"),
  "Bobby": require("./Bobby.png"),
  "Brown Door": require("./Brown_Door.png"),
  "CabinetA01": require("./CabinetA01.png"),
  "CabinetACorner01": require("./CabinetACorner01.png"),
  "CabinetA_Sink": require("./CabinetA_Sink.png"),
  "CabinetB01": require("./CabinetB01.png"),
  "CabinetB03": require("./CabinetB03.png"),
  "CabinetB_Sink": require("./CabinetB_Sink.png"),
  "Chair01": require("./Chair01.png"),
  "Chair02": require("./Chair02.png"),
  "Closet01": require("./Closet01.png"),
  "Closet02": require("./Closet02.png"),
  "Closet03": require("./Closet03.png"),
  "Closet04": require("./Closet04.png"),
  "Closet05": require("./Closet05.png"),
  "Closet06": require("./Closet06.png"),
  "Closet07": require("./Closet07.png"),
  "Closet08": require("./Closet08.png"),
  "Closet09": require("./Closet09.png"),
  "Closet10": require("./Closet10.png"),
  "Closet11": require("./Closet11.png"),
  "Closet12": require("./Closet12.png"),
  "Drawer01": require("./Drawer01.png"),
  "Drawer02": require("./Drawer02.png"),
  "Drawer03": require("./Drawer03.png"),
  "Drawer04": require("./Drawer04.png"),
  "File Cabinet01": require("./File_Cabinet01.png"),
  "Freddy": require("./Freddy.png"),
  "Hostile": require("./Hostile.png"),
  "Non-Hostile": require("./Non-Hostile.png"),
  "Open Door Frame": require("./Open_Door_Frame.png"),
  "Ray": require("./Ray.png"),
  "Remy": require("./Remy.png"),
  "Sofa01": require("./Sofa01.png"),
  "Sofa02": require("./Sofa02.png"),
  "Sofa03": require("./Sofa03.png"),
  "Sofa04": require("./Sofa04.png"),
  "Sofa05": require("./Sofa05.png"),
  "Sofa06": require("./Sofa06.png"),
  "Sofa07": require("./Sofa07.png"),
  "Sofa08": require("./Sofa08.png"),
  "Sofa09": require("./Sofa09.png"),
  "Sofa10": require("./Sofa10.png"),
  "Sofa11": require("./Sofa11.png"),
  "Sofa12": require("./Sofa12.png"),
  "Sofa13": require("./Sofa13.png"),
  "Soldier": require("./Soldier.png"),
  "Soldier (Gas)": require("./Soldier_Gas.png"),
  "Susan": require("./Susan.png"),
  "Tabby": require("./Tabby.png"),
  "Table01": require("./Table01.png"),
  "Table02": require("./Table02.png"),
  "Table03": require("./Table03.png"),
  "Table04": require("./Table04.png"),
  "Table05": require("./Table05.png"),
  "Table06": require("./Table06.png"),
  "Table07": require("./Table07.png"),
  "Table08": require("./Table08.png"),
  "Table09": require("./Table09.png"),
  "Table10": require("./Table10.png"),
  "Table11": require("./Table11.png"),
  "Toilet01": require("./Toilet01.png"),
  "Tom": require("./Tom.png"),
  "White Door": require("./White_Door.png"),
};

export const thumbFor = (kind: string): number | undefined => THUMBS[kind];
